### ISSUE TITLE
Restrict master branch

### ISSUE THREAD

**Issue by abrarShariar** [TheHeisenbugs/Sustainable-Tourism#5]
Since our workflow will be based on creating individual branch for each member so, we will have 6 different branch (each for one member) and a master branch.Now each member will use their definite branch as their code repo.

Currently any member can merge with the master branch from their own branch.This can be conflicting  and since most of us are not well skilled in using git so resolving any merge conflict will be difficult. I think the merge privilege should be restricted and well controlled so, that each member can sent 'Pull Request' from their branch but only an admin will be able to review and merge with the master.

**Comment by SohanChy** [comment]
@TheHeisenbugs/alphateam What do you guys think?

I don't even know if git has such an option to restrict team members from merging to their own project.
I know theres a thing called protected branches, but I think thats for deletions and force pushes only.

**Comment by ehzawad** [comment]
Not a bad idea...
